const moviesData = [
    {
        id: 1,
        poster: "images/AcrossTheSpiderVerse.png",
        name: "Across the Spiderverse",
        releaseDate: "June 02, 2023",
        rating: "4.3/5",
        link: "https://en.wikipedia.org/wiki/Spider-Man:_Across_the_Spider-Verse",
    },
    {
        id: 2,
        poster: "images/JujutsuKaisen0.png",
        name: "Jujutsu Kaisen 0",
        releaseDate: "March 18, 2022",
        rating: "4.8/5",
        link: "https://en.wikipedia.org/wiki/Jujutsu_Kaisen_0_(film)",
    },
    {
        id: 3,
        poster: "images/AvengersEndgame.png",
        name: "Avengers Endgame",
        releaseDate: "April 26, 2019",
        rating: "4.7/5",
        link: "https://en.wikipedia.org/wiki/Avengers:_Endgame",
    },
    {
        id: 4,
        poster: "images/birthofanation.png",
        name: "The Birth of a Nation",
        releaseDate: "October 7, 2016",
        rating: "4.6/5",
        link: "https://en.wikipedia.org/wiki/The_Birth_of_a_Nation_(2016_film)",
    },
    {
        id: 5,
        poster: "images/minecraftmovie.png",
        name: "A Minecraft Movie",
        releaseDate: "April 04, 2025",
        rating: "4.0/5",
        link: "https://en.wikipedia.org/wiki/A_Minecraft_Movie",
    },
    {
        id: 6,
        poster: "images/sonic3.png",
        name: "Sonic 3",
        releaseDate: "December 20, 2024",
        rating: "4.7/5",
        link: "https://en.wikipedia.org/wiki/Sonic_the_Hedgehog_3_(film)",
    },
    {
        id: 7,
        poster: "images/havoc.png",
        name: "Havoc",
        releaseDate: "April 25, 2025",
        rating: "3.0/5",
        link: "https://en.wikipedia.org/wiki/Havoc_(2025_film)",
    },
    {
        id: 8,
        poster: "images/cokebear.png",
        name: "Cocaine Bear",
        releaseDate: "February 24, 2023",
        rating: "3.2/5",
        link: "https://en.wikipedia.org/wiki/Cocaine_Bear",
    },
    {
        id: 9,
        poster: "images/twister.png",
        name: "Twister",
        releaseDate: "May 10, 1996",
        rating: "4.2/5",
        link: "https://en.wikipedia.org/wiki/Twister_(1996_film)",
    },
    {
        id: 10,
        poster: "images/doghotel.png",
        name: "Hotel for Dogs",
        releaseDate: "January 16, 2009",
        rating: "4.7/5",
        link: "https://en.wikipedia.org/wiki/Hotel_for_Dogs_(film)",
    },
    {
        id: 11,
        poster: "images/shrek.png",
        name: "Shrek",
        releaseDate: "May 18, 2001",
        rating: "4.5/5",
        link: "https://en.wikipedia.org/wiki/Shrek",
    },
    {
        id: 12,
        poster: "images/darkknight.png",
        name: "The Dark Knight",
        releaseDate: "July 18, 2008",
        rating: "4.9/5",
        link: "https://en.wikipedia.org/wiki/The_Dark_Knight",
    },
    {
        id: 13,
        poster: "images/SpyKids.png",
        name: "Spy Kids 3-D: Game over",
        releaseDate: "July 25, 2003",
        rating: "4.0/5",
        link: "https://en.wikipedia.org/wiki/Spy_Kids_3-D:_Game_Over",
    },
    {
        id: 14,
        poster: "images/despicable.png",
        name: "Despicable Me 4",
        releaseDate: "July 3, 2024",
        rating: "3.7/5",
        link: "https://en.wikipedia.org/wiki/Despicable_Me_4",
    },
    {
        id: 15,
        poster: "images/loudhouse.png",
        name: "The Loud House Movie",
        releaseDate: "August 20, 2021",
        rating: "4.1/5",
        link: "https://en.wikipedia.org/wiki/The_Loud_House_Movie",
    },
    {
        id: 16,
        poster: "images/lavaboysharkgirl.png",
        name: "Sharkboy and Lavagirl",
        releaseDate: "June 10, 2005",
        rating: "4.1/5",
        link: "https://en.wikipedia.org/wiki/The_Adventures_of_Sharkboy_and_Lavagirl_in_3-D",
    },
    {
        id: 17,
        poster: "images/surfsdown.png",
        name: "Surf's Up 2: WaveMania",
        releaseDate: "January 17, 2017",
        rating: "2.3/5",
        link: "https://en.wikipedia.org/wiki/Surf%27s_Up_2:_WaveMania",
    },
    {
        id: 18,
        poster: "images/fred3.png",
        name: "Fred 3: Camp Fred",
        releaseDate: "July 28, 2012",
        rating: "4.1/5",
        link: "https://en.wikipedia.org/wiki/Fred_3:_Camp_Fred",
    },
    {
        id: 19,
        poster: "images/peebodyandsureman.png",
        name: "Mr. Peabody & Sherman",
        releaseDate: "March 7, 2014",
        rating: "4.6/5",
        link: "https://en.wikipedia.org/wiki/Mr._Peabody_%26_Sherman",
    },
    {
        id: 20,
        poster: "images/alvinchip.png",
        name: "Alvin & Chipmunks: Chipwrecked",
        releaseDate: "December 16, 2011",
        rating: "4.3/5",
        link: "https://en.wikipedia.org/wiki/Alvin_and_the_Chipmunks:_Chipwrecked",
    },
    {
        id: 21,
        poster: "images/enaf.png",
        name: "Eight Crazy Nights",
        releaseDate: "November 27, 2002",
        rating: "4.1/5",
        link: "https://en.wikipedia.org/wiki/Eight_Crazy_Nights",
    },
    {
        id: 22,
        poster: "images/underpanties.png",
        name: "Captain Underpants",
        releaseDate: "June 2, 2017",
        rating: "4.7/5",
        link: "https://en.wikipedia.org/wiki/Captain_Underpants:_The_First_Epic_Movie",
    },
    {
        id: 23,
        poster: "images/pixel.png",
        name: "Pixels",
        releaseDate: "July 24, 2015",
        rating: "4.3/5",
        link: "https://en.wikipedia.org/wiki/Pixels_(2015_film)",
    },
    {
        id: 23,
        poster: "images/kidspy4.png",
        name: "Spy Kids: All the Time in the World",
        releaseDate: "August 19, 2011",
        rating: "3.4/5",
        link: "https://en.wikipedia.org/wiki/Spy_Kids:_All_the_Time_in_the_World",
    },
    {
        id: 24,
        poster: "images/karatekid.png",
        name: "The Karate Kid",
        releaseDate: "June 11, 2010",
        rating: "4.4/5",
        link: "https://en.wikipedia.org/wiki/The_Karate_Kid_(2010_film)",
    },
    {
        id: 25,
        poster: "images/croods.png",
        name: "The Croods",
        releaseDate: "March 22, 2013",
        rating: "4.6/5",
        link: "https://en.wikipedia.org/wiki/The_Croods",
    },
];
